apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{applicationName}}
  namespace: {{namespace}}
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8080
  accessPolicy:
    outbound:
      external:
        - host: "appres.nav.no"
        - host: "nav.psplugin.com"
      rules:
        - application: sosialhjelp-veiviser
        - application: sosialhjelp-soknad
        - application: sosialhjelp-soknad-api
        - application: sosialhjelp-innsyn
        - application: sosialhjelp-innsyn-api
        - application: sosialhjelp-modia
        - application: sosialhjelp-modia-api
        - application: sosialhjelp-mock-alt-api
        - application: sosialhjelp-fagsystem-mock
    inbound:
      rules:
        - application: sosialhjelp-soknad-api
        - application: sosialhjelp-innsyn-api
        - application: sosialhjelp-modia-api
  ingresses:
{{#each ingresses}}
    - "{{this}}"
{{/each}}
  prometheus:
    enabled: false
    path: /prometheus
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isAlive
    initialDelay: 20
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  webproxy: true
  env:
    - name: PORT
      value: "8080"
    - name: DOMENE
      value: {{domene}}
